# ==========================================
# APPLICATION
# ==========================================

spring.application.name=eureka-server


# ==========================================
# SERVER
# ==========================================

server.port=8761


# ==========================================
# EUREKA SERVER
# ==========================================

# Eureka server does not register itself
eureka.client.register-with-eureka=false

# Eureka server does not need to fetch registry
eureka.client.fetch-registry=false

# Eureka server URL
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/


# ==========================================
# EUREKA INSTANCE
# ==========================================

eureka.instance.hostname=localhost


# ==========================================
# LOGGING
# ==========================================

logging.level.com.netflix.eureka=INFO
logging.level.com.netflix.discovery=INFO