# =========================================================
# APPLICATION
# =========================================================

spring.application.name=api-gateway

server.port=8080


# =========================================================
# EUREKA
# =========================================================

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true


# =========================================================
# AUTH SERVICE
# =========================================================

spring.cloud.gateway.routes[0].id=auth-service

spring.cloud.gateway.routes[0].uri=lb://auth-service

spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[0].filters[1]=CircuitBreaker=authCircuitBreaker,fallbackUri=forward:/fallback/auth


# =========================================================
# USER SERVICE
# =========================================================

spring.cloud.gateway.routes[1].id=user-service

spring.cloud.gateway.routes[1].uri=lb://user-service

spring.cloud.gateway.routes[1].predicates[0]=Path=/api/users/**

spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[1].filters[1]=CircuitBreaker=userCircuitBreaker,fallbackUri=forward:/fallback/users


# =========================================================
# NOTES SERVICE
# =========================================================

spring.cloud.gateway.routes[2].id=notes-service

spring.cloud.gateway.routes[2].uri=lb://notes-service

spring.cloud.gateway.routes[2].predicates[0]=Path=/api/notes/**

spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[2].filters[1]=CircuitBreaker=notesCircuitBreaker,fallbackUri=forward:/fallback/notes


# =========================================================
# LABEL SERVICE
# =========================================================

spring.cloud.gateway.routes[3].id=label-service

spring.cloud.gateway.routes[3].uri=lb://notes-service

spring.cloud.gateway.routes[3].predicates[0]=Path=/api/labels/**

spring.cloud.gateway.routes[3].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[3].filters[1]=CircuitBreaker=labelCircuitBreaker,fallbackUri=forward:/fallback/notes


# =========================================================
# REMINDER SERVICE
# =========================================================

spring.cloud.gateway.routes[4].id=reminder-service

spring.cloud.gateway.routes[4].uri=lb://reminder-service

spring.cloud.gateway.routes[4].predicates[0]=Path=/api/reminders/**

spring.cloud.gateway.routes[4].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[4].filters[1]=CircuitBreaker=reminderCircuitBreaker,fallbackUri=forward:/fallback/reminders


# =========================================================
# NOTIFICATION SERVICE
# =========================================================

spring.cloud.gateway.routes[5].id=notification-service

spring.cloud.gateway.routes[5].uri=lb://notification-service

spring.cloud.gateway.routes[5].predicates[0]=Path=/api/notifications/**

spring.cloud.gateway.routes[5].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[5].filters[1]=CircuitBreaker=notificationCircuitBreaker,fallbackUri=forward:/fallback/notifications


# =========================================================
# EXPORT SERVICE
# =========================================================

spring.cloud.gateway.routes[6].id=export-service

spring.cloud.gateway.routes[6].uri=lb://export-service

spring.cloud.gateway.routes[6].predicates[0]=Path=/api/export/**

spring.cloud.gateway.routes[6].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[6].filters[1]=CircuitBreaker=exportCircuitBreaker,fallbackUri=forward:/fallback/export


# =========================================================
# DISCOVERY LOCATOR
# =========================================================

spring.cloud.gateway.discovery.locator.enabled=false


# =========================================================
# RESILIENCE4J
# =========================================================

resilience4j.circuitbreaker.instances.authCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.authCircuitBreaker.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.authCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.authCircuitBreaker.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.authCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.authCircuitBreaker.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.authCircuitBreaker.permittedNumberOfCallsInHalfOpenState=3


resilience4j.circuitbreaker.instances.userCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.userCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.userCircuitBreaker.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.userCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.userCircuitBreaker.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.userCircuitBreaker.permittedNumberOfCallsInHalfOpenState=3


resilience4j.circuitbreaker.instances.notesCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.notesCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.notesCircuitBreaker.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.notesCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.notesCircuitBreaker.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.notesCircuitBreaker.permittedNumberOfCallsInHalfOpenState=3


resilience4j.circuitbreaker.instances.labelCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.labelCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.labelCircuitBreaker.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.labelCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.labelCircuitBreaker.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.labelCircuitBreaker.permittedNumberOfCallsInHalfOpenState=3


resilience4j.circuitbreaker.instances.reminderCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.reminderCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.reminderCircuitBreaker.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.reminderCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.reminderCircuitBreaker.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.reminderCircuitBreaker.permittedNumberOfCallsInHalfOpenState=3


resilience4j.circuitbreaker.instances.notificationCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.notificationCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.notificationCircuitBreaker.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.notificationCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.notificationCircuitBreaker.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.notificationCircuitBreaker.permittedNumberOfCallsInHalfOpenState=3


resilience4j.circuitbreaker.instances.exportCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.exportCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.exportCircuitBreaker.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.exportCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.exportCircuitBreaker.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.exportCircuitBreaker.permittedNumberOfCallsInHalfOpenState=3


# =========================================================
# LOGGING
# =========================================================

logging.level.org.springframework.cloud.gateway=INFO

logging.level.io.github.resilience4j=INFO

logging.level.org.springframework.cloud.netflix.eureka=INFO

logging.level.com.netflix.discovery=INFO